# Generated by Django 4.0.1 on 2022-03-03 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestate',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gamestate',
            name='winner',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='deck',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='username',
            field=models.TextField(null=True),
        ),
    ]
